# Generated by Django 3.2.5 on 2021-07-14 16:56

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='date created')),
                ('genus', models.CharField(max_length=200)),
                ('species', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('parent1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_parent_strain', to='strainlib.strain')),
                ('parent2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_parent_strain', to='strainlib.strain')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='date created')),
                ('name', models.CharField(max_length=200)),
                ('root1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_root_strain', to='strainlib.strain')),
                ('root2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_root_strain', to='strainlib.strain')),
            ],
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(verbose_name='date created')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strainlib.project')),
            ],
        ),
    ]
