# Generated by Django 3.2.5 on 2021-07-14 20:27

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('strainlib', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='strain',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='strain',
            name='stable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='strain',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='strain',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='strain',
            name='parent1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_parent_strain', to='strainlib.strain'),
        ),
        migrations.AlterField(
            model_name='strain',
            name='parent2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_parent_strain', to='strainlib.strain'),
        ),
        migrations.AlterField(
            model_name='strain',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
