# Generated by Django 3.2.5 on 2021-07-17 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strainlib', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generation',
            name='f_number',
        ),
        migrations.RemoveField(
            model_name='project',
            name='gen_count',
        ),
    ]
