# Generated by Django 3.2.5 on 2021-07-17 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strainlib', '0002_auto_20210717_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generation',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RemoveField(
            model_name='strain',
            name='in_projects',
        ),
        migrations.AddField(
            model_name='strain',
            name='in_generations',
            field=models.ManyToManyField(blank=True, to='strainlib.Generation'),
        ),
    ]
