# Generated by Django 3.2.5 on 2021-07-14 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strainlib', '0002_auto_20210714_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='stable',
            field=models.BooleanField(default=True),
        ),
    ]
