# Generated by Django 3.2.5 on 2021-07-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strainlib', '0003_auto_20210717_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strain',
            name='in_generations',
        ),
        migrations.AddField(
            model_name='generation',
            name='children',
            field=models.ManyToManyField(blank=True, to='strainlib.Strain'),
        ),
    ]
