# Generated by Django 3.2.5 on 2021-07-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strainlib', '0003_strain_stable'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
