# Generated by Django 3.2.5 on 2021-07-17 18:47

from django.db import migrations, models
import django.db.models.deletion
import strainlib.models


class Migration(migrations.Migration):

    dependencies = [
        ('strainlib', '0004_auto_20210717_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='f_number',
            field=models.IntegerField(default=strainlib.models.Generation.increment_f_number, editable=False),
        ),
        migrations.AlterField(
            model_name='generation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='strainlib.project'),
        ),
    ]
