# Generated by Django 3.2.5 on 2021-07-17 19:11

from django.db import migrations, models
import strainlib.models


class Migration(migrations.Migration):

    dependencies = [
        ('strainlib', '0005_auto_20210717_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generation',
            name='f_number',
            field=models.CharField(default=strainlib.models.Generation.increment_f_number, editable=False, max_length=200),
        ),
    ]
