# Generated by Django 3.2.5 on 2021-07-17 19:40

from django.db import migrations, models
import django.db.models.deletion
import strainlib.models


class Migration(migrations.Migration):

    dependencies = [
        ('strainlib', '0006_alter_generation_f_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generation',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='generations',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='strainlib.generation'),
        ),
        migrations.AlterField(
            model_name='generation',
            name='f_number',
            field=models.IntegerField(default=1, editable=True),
        ),
    ]
