# Generated by Django 3.2.5 on 2021-07-17 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strainlib', '0007_auto_20210717_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='generations',
        ),
        migrations.AddField(
            model_name='generation',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='strainlib.project'),
        ),
    ]
