# Generated by Django 3.2.5 on 2021-07-17 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strainlib', '0008_auto_20210717_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='strainlib.project'),
        ),
    ]
