# Generated by Django 3.2.5 on 2021-07-17 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strainlib', '0009_alter_generation_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generation',
            name='f_number',
        ),
    ]
