# Generated by Django 3.2.5 on 2021-07-17 20:09

from django.db import migrations, models
import strainlib.models


class Migration(migrations.Migration):

    dependencies = [
        ('strainlib', '0010_remove_generation_f_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='generation',
            name='f_number',
            field=models.IntegerField(default=1),
        ),
    ]
