# Generated by Django 3.2.5 on 2021-07-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strainlib', '0011_generation_f_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generation',
            name='f_number',
            field=models.IntegerField(default=1),
        ),
    ]
