# Generated by Django 3.2.5 on 2021-07-26 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strainlib', '0013_remove_generation_f_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='root1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='root2',
        ),
        migrations.DeleteModel(
            name='Generation',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
