# Generated by Django 3.2.5 on 2021-07-26 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('strainlib', '0014_auto_20210726_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('name', models.CharField(default='New breeding project', max_length=200)),
                ('latest_generation', models.IntegerField(default=0)),
                ('root1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_root_strain', to='strainlib.strain')),
                ('root2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_root_strain', to='strainlib.strain')),
            ],
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('f_number', models.IntegerField(default=1, editable=False)),
                ('children', models.ManyToManyField(blank=True, to='strainlib.Strain')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='breedproj.project')),
            ],
        ),
    ]
